title:              Ulil Hidayat Personal Blog
email:              ulil.hidayat2799@gmail.com
description:        Welcome to my personal blog, where I enthusiastically document my ongoing learning journey
author:             Ulil Hidayat
baseurl:            ""
url:                "https://ulil-hidayat.github.io"

# Social Profiles
twitter_username:   
github_username:    ulil-hidayat.github
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
